### ISSUE TITLE
add_lcsi treating NA

### ISSUE THREAD

**Issue by RedEggplant1** [impact-initiatives/addindicators#20]
The function throws an error when there are NA values in any strategy (because the function count 5 lcs_codes, which stops the running). We should define how NAs must be treated (not sure what the rule is).

![MicrosoftTeams-image (3)](https://github.com/impact-initiatives/addindicators/assets/63230276/cb83ab0e-227e-44ec-9857-1e741ef10642)
![MicrosoftTeams-image (4)](https://github.com/impact-initiatives/addindicators/assets/63230276/ef126149-5bfc-428e-a793-149798b82a4d)

**Comment by yannsay-impact** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add_lcsi cannot handle NA values](https://trello.com/c/lpex1Oz6/215-addlcsi-cannot-handle-na-values)

**Comment by yannsay-impact** [comment]
resolve, see #21
