### ISSUE TITLE
add_fcs throws a weird error

### ISSUE THREAD

**Issue by RedEggplant1** [impact-initiatives/addindicators#29]
add_fcs throws a mysterious error, not sure why.
I did a few checks
- all fcs_ variables are of type "double"
- there is no type in the var names, all of them exist in the data and have values

hh %>% add_fcs(cutoffs = "normal 21.5-35", fcs_cereal = "fcs_cereal", fcs_legumes = "fcs_pulses", fcs_veg = "fcs_veg", fcs_fruit = "fcs_fruit", fcs_meat = "fcs_meat", fcs_dairy = "fcs_milk", fcs_sugar = "fcs_sugar", fcs_oil = "fcs_oil")

Error in `dplyr::mutate()`:
ℹ In argument: `fcs_weight_cereal1 = ifelse(is.na(df[[fcs_cereal]]), NA, df[[fcs_cereal]] * 2)`.
Caused by error in `.subset2()`:
! recursive indexing failed at level 2
Backtrace:
  1. hh %>% ...
 14. base::`[[.data.frame`(df, fcs_cereal)

**Comment by AbrahamAz** [comment]
This one is already fixed with the new pull request
